export const STORAGE_KEY = "daily-goals-final";
export const PREFS_KEY = "taskflow-prefs-v1";
export const UI_STATE_KEY = "taskflow-ui-v1";
export const TOOLS_KEY = "taskflow-tools-v1";
export const CAREER_KEY = "taskflow-career-v1";
export const HABITS_KEY = "taskflow-habits-v1";
export const JOURNAL_KEY = "taskflow-journal-v1";
export const GOALS_KEY = "taskflow-goals-v1";
export const LANGUAGE_OPTIONS = [
  { label: "English", value: "en" },
  { label: "Tamil", value: "ta" },
];

export const REPEAT_OPTIONS = ["None", "Daily", "Weekly", "Monthly"];
export const SESSION_OPTIONS = ["Morning", "Afternoon", "Evening"];
export const PRIORITY_OPTIONS = ["Low", "Medium", "High"];

export const FONT_OPTIONS = [
  { label: "Söhne/Inter", value: "'Söhne', 'Inter', 'DM Sans', ui-sans-serif, system-ui, sans-serif" },
  { label: "Segoe UI", value: '"Segoe UI Variable","Segoe UI",sans-serif' },
  { label: "Poppins", value: '"Poppins","Segoe UI",sans-serif' },
  { label: "Montserrat", value: '"Montserrat","Segoe UI",sans-serif' },
  { label: "Nunito", value: '"Nunito","Segoe UI",sans-serif' },
  { label: "Times New Roman", value: '"Times New Roman",Times,serif' },
];

export const THEME_OPTIONS = [
  { label: "Dark", value: "dark" },
  { label: "Ocean Dark", value: "ocean-dark" },
  { label: "Midnight", value: "midnight" },
  { label: "Cyber Neon", value: "cyber-neon" },
  { label: "Deep Purple", value: "deep-purple" },
  { label: "Emerald Night", value: "emerald-night" },
  { label: "Eye Comfort", value: "eye-comfort" },
  { label: "Sunset Light", value: "sunset-light" },
  { label: "Forest Mist", value: "forest-mist" },
  { label: "Rose Dawn", value: "rose-dawn" },
  { label: "Lavender Night", value: "lavender-night" },
  { label: "Mocha Espresso", value: "mocha-espresso" },
  { label: "Sakura Bloom", value: "sakura-bloom" },
  { label: "Graphite Lime", value: "graphite-lime" },
  { label: "Arctic Glass", value: "arctic-glass" },
];

export const TIME_FILTER_OPTIONS = ["All Times", "Morning", "Afternoon", "Evening", "Night", "No Time"];
export const DAY_NAMES = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];

export const QUOTES = [
  "Small steps every day lead to big results.",
  "Progress, not perfection.",
  "Dream it. Plan it. Do it.",
  "Focus on progress, not pressure.",
  "The secret of getting ahead is getting started.",
  "Don't watch the clock; do what it does. Keep going.",
  "Action is the foundational key to all success.",
  "You don't have to be great to start, but you have to start to be great.",
  "A year from now you'll wish you had started today.",
  "Discipline is choosing between what you want now and what you want most.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The only way to do great work is to love what you do.",
  "What you do today can improve all your tomorrows.",
  "It always seems impossible until it's done.",
  "Hard work beats talent when talent doesn't work hard.",
  "Your future is created by what you do today, not tomorrow.",
  "Strive for progress, not perfection.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Believe you can and you're halfway there.",
  "Don't limit your challenges. Challenge your limits.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let success make the noise.",
];

export const PRIORITY_RANK = { High: 0, Medium: 1, Low: 2 };

export const APP_COPY = {
  en: {
    tabs: {
      insights: "Dashboard",
      tasks: "Tasks",
      planner: "Planner",
      analytics: "Analytics",
      settings: "Settings",
      career: "Career",
      tools: "Tools",
      habits: "Habits",
      journal: "Journal",
      goals: "Goals",
      more: "More",
    },
    common: {
      todayFocus: "Today's Focus",
      tasks: "Tasks",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      task: "Task",
      time: "Time",
      session: "Session",
      enable: "Enable",
      refresh: "Refresh",
      run: "Run",
      close: "Close",
      export: "Export",
      search: "Search",
      tamil: "Tamil",
      today: "Today",
      gotIt: "Got it",
      create: "Create",
      addTask: "Add Task",
      saveChanges: "Save Changes",
      loading: "Loading",
    },
    settings: {
      title: "Settings",
      subtitle: "Personalize, clean up, and keep the app healthy",
      language: "Language",
      languageSubtitle: "Choose app language",
      battery: "Battery Protection",
      batterySubtitle: "Open Android settings and keep notifications alive",
      batteryGuide: "Disable battery optimization for this app so alarms keep firing after close or recent-app clear.",
      openBattery: "Open Battery Settings",
      openApp: "Open App Settings",
      profile: "Profile",
      notifications: "Notifications",
      theme: "Theme",
      display: "Display",
      behavior: "Behavior",
      storage: "Storage",
      preview: "Preview",
      reset: "Reset",
    },
    tools: {
      title: "Working Tools",
      quickNotes: "Quick Notes",
      notesLocker: "Notes Locker",
      noteTitle: "Note title",
      noteBody: "Save proper notes here. These stay in the app until you delete them.",
      saveNote: "Save Note",
      noNotes: "No saved notes yet.",
      pinned: "Pinned",
      searchNotes: "Search saved notes...",
      exportNotes: "Export Notes",
      brainDump: "Brain Dump",
      boxBreathing: "Box Breathing",
      eveningReview: "Evening Daily Review",
    },
    analytics: {
      title: "Productivity Analytics",
      subtitle: "Track your productivity patterns and insights",
      aiWeekly: "AI Weekly Analysis",
      forecast: "Forecast",
      nextWeek: "Next Week Auto Plan",
      quickTools: "Quick Tools",
      createNextWeekPlan: "Create Next Week Plan",
      planReady: "Plan Ready",
      workloadBalance: "Workload Balance",
      focusTime: "Focus Time",
      burnoutRisk: "Burnout Risk",
      cleanup: "Cleanup",
      trend: "Trend",
      predictedNextWeek: "Predicted Next Week",
      summary: "Summary",
      momentum: "Momentum",
      pattern: "Pattern",
      advice: "Advice",
      startPomodoro: "Start Pomodoro",
      exportTasks: "Export Tasks",
      viewTasks: "View Tasks",
      openPlanner: "Open Planner",
      planCreated: "Next week plan created and added to your board.",
    },
    taskForm: {
      editTask: "Edit Task",
      newTask: "New Task",
      taskDescription: "Task Description",
      taskPlaceholder: "What needs to be done? (e.g. Meeting 9am-10am)",
      taskHint: "Type \"meeting 9am-10am\" to auto-fill time fields",
      aiContext: "AI Context",
      aiContextPlaceholder: "Optional: tell AI your focus, energy level, or preferred schedule style",
      date: "Date",
      startTime: "Start Time",
      endTime: "End Time",
      reminderTime: "Reminder Time",
      priority: "Priority",
      session: "Session",
      repeat: "Repeat",
      aiThinking: "AI is thinking...",
      aiAutoSchedule: "AI Auto-Schedule",
    },
    tasksView: {
      aiCoach: "AI Coach",
      liveMode: "Live Mode",
      focus: "Focus",
      newTask: "New Task",
      aiPlan: "AI Plan",
      currentTask: "Current Task",
      jumpToLive: "Jump to live task",
      todayTasks: "Today's Tasks",
      focusedToday: "Focused Today",
      pendingTasks: "Pending Tasks",
      completedTasks: "Completed Tasks",
      searchPlaceholder: "Search tasks...",
      noPendingSearch: "No pending tasks found matching your search.",
      noPending: "No pending tasks for today. Great job!",
      selectAll: "Select All",
      deleteSelected: "Delete Selected",
      clearSelection: "Clear Selection",
      markAllDone: "Mark All Done",
      copyTomorrow: "Copy to Tomorrow",
      reopenAll: "Reopen All",
      taskActions: "Task Actions",
      selectTask: "Select Task",
      deselectTask: "Deselect Task",
    },
    alerts: {
      nextTaskSoon: "Next task starting soon!",
      taskReminder: "Task Reminder",
    },
    ai: {
      stayLocked: "Stay locked on",
      until: "until",
      prepFor: "Prep for",
      before: "before",
      boardOpen: "Your board is open. Plan one focused block and keep the rest light.",
      overdueNow: "tasks are overdue right now.",
      overdueSingle: "task is overdue right now.",
      highPriorityWaiting: "High priority waiting:",
      noUrgent: "No urgent blockers detected.",
      assignSlots: "Assign time slots to:",
      goodStructure: "Good structure already. Keep only the next 1 or 2 priorities visible.",
      dayClear: "Day looks clear. This is a good moment to plan tomorrow.",
    },
  },
  ta: {
    tabs: {
      insights: "டாஷ்போர்டு",
      tasks: "பணிகள்",
      planner: "திட்டம்",
      analytics: "பகுப்பாய்வு",
      settings: "அமைப்புகள்",
      career: "கேரியர்",
      tools: "கருவிகள்",
      habits: "பழக்கங்கள்",
      journal: "ஜர்னல்",
      goals: "இலக்குகள்",
      more: "மேலும்",
    },
    common: {
      todayFocus: "இன்றைய கவனம்",
      tasks: "பணிகள்",
      cancel: "ரத்து",
      save: "சேமிக்க",
      enable: "இயக்கு",
      refresh: "புதுப்பிக்க",
      run: "திற",
      close: "மூடு",
      export: "ஏற்றுமதி",
      search: "தேடு",
      tamil: "தமிழ்",
    },
    settings: {
      title: "அமைப்புகள்",
      subtitle: "அப்பை உங்களுக்குப் பொருத்தமாக மாற்றுங்கள்",
      language: "மொழி",
      languageSubtitle: "அப் மொழியை தேர்வு செய்யவும்",
      battery: "பேட்டரி பாதுகாப்பு",
      batterySubtitle: "Android settings திறந்து notifications வேலை செய்ய வையுங்கள்",
      batteryGuide: "இந்த appக்கு battery optimization off செய்தால் close ஆன பிறகும் reminders நன்றாக வரும்.",
      openBattery: "Battery Settings திற",
      openApp: "App Settings திற",
      profile: "சுயவிவரம்",
      notifications: "அறிவிப்புகள்",
      theme: "தீம்",
      display: "திரை",
      behavior: "நடத்தை",
      storage: "சேமிப்பு",
      preview: "முன்னோட்டம்",
      reset: "ரீசெட்",
    },
    tools: {
      title: "வேலை கருவிகள்",
      quickNotes: "விரைவு குறிப்புகள்",
      notesLocker: "குறிப்பு சேமிப்பு",
      noteTitle: "குறிப்பு தலைப்பு",
      noteBody: "இங்கே குறிப்புகளை சேமிக்கலாம். நீங்க delete பண்ணும் வரை இருக்கும்.",
      saveNote: "குறிப்பை சேமிக்க",
      noNotes: "இன்னும் சேமித்த குறிப்புகள் இல்லை.",
      pinned: "பின் செய்யப்பட்டது",
      searchNotes: "சேமித்த குறிப்புகளை தேடுங்கள்...",
      exportNotes: "குறிப்புகளை ஏற்றுமதி செய்",
      brainDump: "மனச்சுமை வெளியேற்று",
      boxBreathing: "சுவாச பயிற்சி",
      eveningReview: "மாலை தினசரி விமர்சனம்",
    },
    analytics: {
      title: "உற்பத்தித்திறன் பகுப்பாய்வு",
      subtitle: "உங்கள் வேலை முன்னேற்றத்தை பாருங்கள்",
      aiWeekly: "AI வாராந்திர பகுப்பாய்வு",
      forecast: "முன்கணிப்பு",
      nextWeek: "அடுத்த வார தானியங்கி திட்டம்",
      quickTools: "விரைவு கருவிகள்",
    },
  },
};

Object.assign(APP_COPY.ta.common, {
  edit: "திருத்து",
  delete: "நீக்கு",
  task: "பணி",
  time: "நேரம்",
  session: "அமர்வு",
  today: "இன்று",
  gotIt: "சரி",
  create: "உருவாக்கு",
  addTask: "பணி சேர்க்க",
  saveChanges: "மாற்றங்களை சேமிக்க",
  loading: "ஏற்றுகிறது",
});

Object.assign(APP_COPY.ta.analytics, {
  createNextWeekPlan: "அடுத்த வார திட்டத்தை உருவாக்கு",
  planReady: "திட்டம் தயார்",
  workloadBalance: "பணி சமநிலை",
  focusTime: "கவன நேரம்",
  burnoutRisk: "சோர்வு அபாயம்",
  cleanup: "சுத்தப்படுத்தல்",
  trend: "போக்கு",
  predictedNextWeek: "அடுத்த வார கணிப்பு",
  summary: "சுருக்கம்",
  momentum: "முன்னேற்றம்",
  pattern: "முறை",
  advice: "ஆலோசனை",
  startPomodoro: "பொமொடோரோ தொடங்கு",
  exportTasks: "பணிகளை ஏற்று",
  viewTasks: "பணிகளை பாருங்கள்",
  openPlanner: "திட்டத்தை திற",
  planCreated: "அடுத்த வார திட்டம் உங்கள் பட்டியலில் சேர்க்கப்பட்டது.",
  burnoutHigh: "அதிகம்",
  burnoutMedium: "நடுத்தரம்",
  burnoutLow: "குறைவு",
});

APP_COPY.en.taskForm = {
  editTask: "Edit Task",
  newTask: "New Task",
  taskDescription: "Task Description",
  taskPlaceholder: "What needs to be done? (e.g. Meeting 9am-10am)",
  taskHint: "Type \"meeting 9am-10am\" to auto-fill time fields",
  aiContext: "AI Context",
  aiContextPlaceholder: "Optional: tell AI your focus, energy level, or preferred schedule style",
  date: "Date",
  startTime: "Start Time",
  endTime: "End Time",
  reminderTime: "Reminder Time",
  priority: "Priority",
  session: "Session",
  repeat: "Repeat",
  aiThinking: "AI is thinking...",
  aiAutoSchedule: "AI Auto-Schedule",
};

Object.assign(APP_COPY.en.analytics, {
  burnoutHigh: "High",
  burnoutMedium: "Medium",
  burnoutLow: "Low",
});

APP_COPY.ta.taskForm = {
  editTask: "பணியை திருத்து",
  newTask: "புதிய பணி",
  taskDescription: "பணி விளக்கம்",
  taskPlaceholder: "எதை செய்ய வேண்டும்? (உதா: Meeting 9am-10am)",
  taskHint: "\"meeting 9am-10am\" என்று type செய்தால் time fields auto-fill ஆகும்",
  aiContext: "AI தகவல்",
  aiContextPlaceholder: "உங்கள் focus, energy level, அல்லது schedule style பற்றி சொல்லலாம்",
  date: "தேதி",
  startTime: "தொடக்க நேரம்",
  endTime: "முடிவு நேரம்",
  reminderTime: "நினைவூட்டு நேரம்",
  priority: "முக்கியம்",
  session: "அமர்வு",
  repeat: "மீண்டும்",
  aiThinking: "AI யோசிக்கிறது...",
  aiAutoSchedule: "AI அட்டவணை அமை",
};

APP_COPY.en.tasksView = {
  aiCoach: "AI Coach",
  liveMode: "Live Mode",
  focus: "Focus",
  newTask: "New Task",
  aiPlan: "AI Plan",
  currentTask: "Current Task",
  jumpToLive: "Jump to live task",
  todayTasks: "Today's Tasks",
  focusedToday: "Focused Today",
  pendingTasks: "Pending Tasks",
  completedTasks: "Completed Tasks",
  searchPlaceholder: "Search tasks...",
  noPendingSearch: "No pending tasks found matching your search.",
  noPending: "No pending tasks for today. Great job!",
  selectAll: "Select All",
  deleteSelected: "Delete Selected",
  clearSelection: "Clear Selection",
  markAllDone: "Mark All Done",
  copyTomorrow: "Copy to Tomorrow",
  reopenAll: "Reopen All",
  taskActions: "Task Actions",
  selectTask: "Select Task",
  deselectTask: "Deselect Task",
};

APP_COPY.ta.tasksView = {
  aiCoach: "AI வழிகாட்டி",
  liveMode: "நேரடி நிலை",
  focus: "கவனம்",
  newTask: "புதிய பணி",
  aiPlan: "AI திட்டம்",
  currentTask: "இப்போதைய பணி",
  jumpToLive: "நேரடி பணிக்கு செல்ல",
  todayTasks: "இன்றைய பணிகள்",
  focusedToday: "இன்றைய மொத்தம்",
  pendingTasks: "மீதமுள்ள பணிகள்",
  completedTasks: "முடிந்த பணிகள்",
  searchPlaceholder: "பணிகளை தேடுங்கள்...",
  noPendingSearch: "தேடலுக்கு பொருந்தும் pending பணிகள் இல்லை.",
  noPending: "இன்றைக்கு pending பணிகள் இல்லை. அருமை!",
  selectAll: "அனைத்தையும் தேர்வு செய்",
  deleteSelected: "தேர்ந்தவற்றை நீக்கு",
  clearSelection: "தேர்வை நீக்கு",
  markAllDone: "அனைத்தையும் முடிந்ததாக குறி",
  copyTomorrow: "நாளைக்கு நகலெடு",
  reopenAll: "மீண்டும் திற",
  taskActions: "பணி செயல்கள்",
  selectTask: "பணியை தேர்வு செய்",
  deselectTask: "தேர்வை நீக்கு",
};

APP_COPY.en.alerts = {
  nextTaskSoon: "Next task starting soon!",
  taskReminder: "Task Reminder",
};

APP_COPY.ta.alerts = {
  nextTaskSoon: "அடுத்த பணி விரைவில் தொடங்கும்!",
  taskReminder: "பணி நினைவூட்டு",
};

APP_COPY.en.ai = {
  stayLocked: "Stay locked on",
  until: "until",
  prepFor: "Prep for",
  before: "before",
  boardOpen: "Your board is open. Plan one focused block and keep the rest light.",
  overdueNow: "tasks are overdue right now.",
  overdueSingle: "task is overdue right now.",
  highPriorityWaiting: "High priority waiting:",
  noUrgent: "No urgent blockers detected.",
  assignSlots: "Assign time slots to:",
  goodStructure: "Good structure already. Keep only the next 1 or 2 priorities visible.",
  dayClear: "Day looks clear. This is a good moment to plan tomorrow.",
};

APP_COPY.ta.ai = {
  stayLocked: "இதில் கவனம் வைத்து செய்யுங்கள்",
  until: "வரை",
  prepFor: "இதற்கு தயார் ஆகுங்கள்",
  before: "முன்",
  boardOpen: "உங்கள் பட்டியல் திறந்துள்ளது. ஒரு focused block மட்டும் திட்டமிட்டு மீதத்தை லேசாக வைத்திருங்கள்.",
  overdueNow: "பணிகள் தற்போது overdue ஆக உள்ளன.",
  overdueSingle: "பணி தற்போது overdue ஆக உள்ளது.",
  highPriorityWaiting: "High priority காத்திருக்கிறது:",
  noUrgent: "அவசரமான தடைகள் இல்லை.",
  assignSlots: "இவைகளுக்கு நேரம் ஒதுக்குங்கள்:",
  goodStructure: "நல்ல அமைப்பு உள்ளது. அடுத்த 1 அல்லது 2 முக்கிய பணிகளை மட்டும் visible ஆக வைத்திருங்கள்.",
  dayClear: "இன்றைய நாள் clear ஆக உள்ளது. நாளைக்கான திட்டம் அமைக்க நல்ல நேரம்.",
};
Object.assign(APP_COPY.en.common, { on: "On", off: "Off" });
Object.assign(APP_COPY.ta.common, { on: "à®‡à®¯à®•à¯à®•à®®à¯", off: "à®¨à®¿à®±à¯à®¤à¯à®¤à®®à¯" });
Object.assign(APP_COPY.en.analytics, {
  predictedNote: "completion chance if current pattern continues.",
  readyTasks: "tasks ready for one-tap creation.",
});
Object.assign(APP_COPY.ta.analytics, {
  predictedNote: "completion chance à®¤à®±à¯à®ªà¯‹à®¤à¯ˆà®¯ pattern à®¤à¯Šà®Ÿà®°à¯à®¨à¯à®¤à®¾à®²à¯.",
  readyTasks: "à®ªà®£à®¿à®•à®³à¯ one-tap creation à®•à¯à®•à¯ à®¤à®¯à®¾à®°à¯.",
});
